[project]
name = "autocopr"
version = "1.0.0"
description = "Check Github Releases daily for new project versions and updates spec files accordingly for automatic COPR updates."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "pyrefly>=1.1.1", # typechecker
    "ruff>=0.16.1", # formatter/linter
]

[tool.uv]
required-version = ">=0.11.0"
exclude-newer = "3 days"

[tool.pyrefly]
project-includes = [ "autocopr", "githubapi" ]
preset = "strict"
min-severity = "warn"
