name: Lint/Format with Ruff

on:
  push:
    branches:
      - main
    paths:
      - "**/*.py"
  pull_request:
    paths:
      - "**/*.py"
  workflow_dispatch:

permissions: {}

jobs:
  lint-fmt-py:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      # Runs `ruff check`
      - uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b # v4.0.0

      # Check formatting
      - run: ruff format --check --diff

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.14'

      # Install deps so they can provide their types
      - run: "python -m pip install --require-hashes --no-deps --only-binary :all: -r requirements.txt"

      - run: "python -m pip install mypy"

      - run: "mypy ."
