name: Lint/Format with Shellcheck

on:
  push:
    branches:
      - main
    paths:
      - "**/*.sh"
  pull_request:
    paths:
      - "**/*.sh"
  workflow_dispatch:

permissions: {}

jobs:
  lint-fmt-sh:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run ShellCheck
        run: find . -type f -name "*.sh" -exec shellcheck {} +
