name: Lint/Format with Shellcheck

on:
  push:
    branches:
      - main
    paths:
      - "**/*.sh"
  pull_request:
    paths:
      - "**/*.sh"
  workflow_dispatch:

permissions: {}

jobs:
  lint-fmt-sh:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run ShellCheck
        run: find . -type f -name "*.sh" -exec shellcheck {} +
