name: Typecheck/Lint/Format with Pyrefly/Ruff

on:
  push:
    branches:
      - main
    paths:
      - "**/*.py"
      - "pyproject.toml"
      - "uv.lock"
  pull_request:
    paths:
      - "**/*.py"
      - "pyproject.toml"
      - "uv.lock"
  workflow_dispatch:

permissions: {}

jobs:
  lint-fmt-py:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39  # v8.2.0

      - name: Format
        run: uv run --locked ruff format --diff

      - name: Lint
        run: uv run --locked ruff check --output-format github

      - name: Typecheck
        run: uv run --locked pyrefly check --output-format github
