name: Lint/Format with Ruff

on:
  push:
    branches:
      - main
    paths:
      - "**/*.py"
  pull_request:
    paths:
      - "**/*.py"
  workflow_dispatch:

permissions: {}

jobs:
  lint-fmt-py:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      # Runs `ruff check`
      - uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6 # v3.6.1

      # Check formatting
      - run: ruff format --check --diff

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.14'

      - run: "python -m pip install types-requests mypy"

      - run: "mypy ."
